service: xkcd

app: xkcd
tenant: chapi

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-3
  memorySize: 2048
  timeout: 60
  versionFunctions: false

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  menu:
    handler: xkcd.comic
    events:
      - http:
          method: get
          path: comic
